<?php

use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('branches')->insert(['name' => 'Alama Iqbal Open University Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '977']);
        DB::table('branches')->insert(['name' => 'Airport Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1575']);
        DB::table('branches')->insert(['name' => 'Pak Secretariat, B. Block Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '880']);
        DB::table('branches')->insert(['name' => 'Blue Area Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '882']);
        DB::table('branches')->insert(['name' => 'Pak Secretariat, D. Block Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '501']);
        DB::table('branches')->insert(['name' => 'F-8 Markaz Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1694']);
        DB::table('branches')->insert(['name' => 'F-10 Markaz Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1933']);
        DB::table('branches')->insert(['name' => 'Foreign Office Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '474']);
        DB::table('branches')->insert(['name' => 'Holiday INN Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1663']);
        DB::table('branches')->insert(['name' => 'Industrial Area Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1531']);
        DB::table('branches')->insert(['name' => 'PARC, Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1539']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '341']);
        DB::table('branches')->insert(['name' => 'Jinnah Avenue Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1628']);
        DB::table('branches')->insert(['name' => 'Margalla Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1725']);
        DB::table('branches')->insert(['name' => 'N.H.Q. Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1469']);
        DB::table('branches')->insert(['name' => 'N.I.H Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1654']);
        DB::table('branches')->insert(['name' => 'P.I.M.S. Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1780']);
        DB::table('branches')->insert(['name' => 'Pinstech Nilor Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '565']);
        DB::table('branches')->insert(['name' => 'P.M. Secretariat Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1732']);
        DB::table('branches')->insert(['name' => 'Pak Secretariat, S. Block Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '485']);
        DB::table('branches')->insert(['name' => 'Tramari Chowk Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '2067']);
        DB::table('branches')->insert(['name' => 'Bhara Kahu Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '2148']);
        DB::table('branches')->insert(['name' => 'Police Foundation Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '2150']);
        DB::table('branches')->insert(['name' => 'Aabpara Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1456']);
        DB::table('branches')->insert(['name' => 'G-9 Markaz Branch', 'region' => 'Islamabad', 'city' => 'Islamabad', 'code' => '1932']);
        DB::table('branches')->insert(['name' => 'Multan Cannt. Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '437']);
        DB::table('branches')->insert(['name' => 'Timber Market Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '835']);
        DB::table('branches')->insert(['name' => 'Fertilizer Factory Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1325']);
        DB::table('branches')->insert(['name' => 'Chowk Dera Adda Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1495']);
        DB::table('branches')->insert(['name' => 'Haram Gate Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1527']);
        DB::table('branches')->insert(['name' => 'Ghalla Mandi Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1602']);
        DB::table('branches')->insert(['name' => 'Nawan Shaher Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1603']);
        DB::table('branches')->insert(['name' => 'Saddar Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1604']);
        DB::table('branches')->insert(['name' => 'Bosan Road Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1931']);
        DB::table('branches')->insert(['name' => 'Nishter Road Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1953']);
        DB::table('branches')->insert(['name' => 'S.R. A Colony Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1995']);
        DB::table('branches')->insert(['name' => 'Mumtazabad Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '1490']);
        DB::table('branches')->insert(['name' => 'Gulgast Colony Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '542']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '375']);
        DB::table('branches')->insert(['name' => 'District Court Branch', 'region' => 'Punjab', 'city' => 'Multan', 'code' => '734']);
        DB::table('branches')->insert(['name' => 'Civil Lines Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '360']);
        DB::table('branches')->insert(['name' => 'University of Agriculture Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '549']);
        DB::table('branches')->insert(['name' => 'Abdullahpur Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '559']);
        DB::table('branches')->insert(['name' => 'AARI Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '560']);
        DB::table('branches')->insert(['name' => 'Factory Area Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '577']);
        DB::table('branches')->insert(['name' => 'Kotwali Road Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '744']);
        DB::table('branches')->insert(['name' => 'Ghulam Muhammadabad Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '840']);
        DB::table('branches')->insert(['name' => 'Noorpur Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '867']);
        DB::table('branches')->insert(['name' => 'Samanabad Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '883']);
        DB::table('branches')->insert(['name' => 'Dry Port Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '1389']);
        DB::table('branches')->insert(['name' => 'Satiana Road Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '476']);
        DB::table('branches')->insert(['name' => 'Clock Tower Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '876']);
        DB::table('branches')->insert(['name' => 'Jinnah Colony Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '1571']);
        DB::table('branches')->insert(['name' => 'DijKot Road Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '1395']);
        DB::table('branches')->insert(['name' => 'Peoples Colony Branch', 'region' => 'Punjab', 'city' => 'Faisalabad', 'code' => '1478']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Jaranwala', 'code' => '342']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '300']);
        DB::table('branches')->insert(['name' => 'Wapda House Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '416']);
        DB::table('branches')->insert(['name' => 'Chauburji Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '493']);
        DB::table('branches')->insert(['name' => 'Krishan Nagar Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '981']);
        DB::table('branches')->insert(['name' => 'Bund Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1996']);
        DB::table('branches')->insert(['name' => 'Badami Bagh Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1997']);
        DB::table('branches')->insert(['name' => 'New Fruit Market Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2121']);
        DB::table('branches')->insert(['name' => 'Rehman Plaza Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1857']);
        DB::table('branches')->insert(['name' => 'Hotel Ambassador Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '483']);
        DB::table('branches')->insert(['name' => 'Pak. Admn. Staff Col. Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '490']);
        DB::table('branches')->insert(['name' => 'Lytton Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '539']);
        DB::table('branches')->insert(['name' => 'PC Hotel Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '628']);
        DB::table('branches')->insert(['name' => 'Davis Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1524']);
        DB::table('branches')->insert(['name' => 'P.P. Assembly Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1948']);
        DB::table('branches')->insert(['name' => 'Patiala Ground Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '313']);
        DB::table('branches')->insert(['name' => 'Anarkali Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '303']);
        DB::table('branches')->insert(['name' => 'Civil Secretariat Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '324']);
        DB::table('branches')->insert(['name' => 'Railway HQs. Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '390']);
        DB::table('branches')->insert(['name' => 'Jinnah Hall Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '413']);
        DB::table('branches')->insert(['name' => 'Shahalam Market Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '757']);
        DB::table('branches')->insert(['name' => 'Dina Nath Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '877']);
        DB::table('branches')->insert(['name' => 'Gawalmandi Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '982']);
        DB::table('branches')->insert(['name' => 'Gulshan-e-Ravi Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2131']);
        DB::table('branches')->insert(['name' => 'LDA Plaza Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '466']);
        DB::table('branches')->insert(['name' => 'Raiwind Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '518']);
        DB::table('branches')->insert(['name' => 'Kahna Nau Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1441']);
        DB::table('branches')->insert(['name' => 'Shahpur Kanjran Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1655']);
        DB::table('branches')->insert(['name' => 'Township Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1669']);
        DB::table('branches')->insert(['name' => 'Faisal Town Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1741']);
        DB::table('branches')->insert(['name' => 'Johar Town Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2069']);
        DB::table('branches')->insert(['name' => 'Raiwind Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2097']);
        DB::table('branches')->insert(['name' => 'Gulberg Model Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1569']);
        DB::table('branches')->insert(['name' => 'DHS T Block Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '323']);
        DB::table('branches')->insert(['name' => 'PCSIR Lab Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '479']);
        DB::table('branches')->insert(['name' => 'Airport Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '496']);
        DB::table('branches')->insert(['name' => 'Wahdat Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '979']);
        DB::table('branches')->insert(['name' => 'Ismail Nagar Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1587']);
        DB::table('branches')->insert(['name' => 'Walton Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1618']);
        DB::table('branches')->insert(['name' => 'DHA Y-Block Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1966']);
        DB::table('branches')->insert(['name' => 'ACP Model Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1442']);
        DB::table('branches')->insert(['name' => 'Samanabad Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '449']);
        DB::table('branches')->insert(['name' => 'Multan Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1606']);
        DB::table('branches')->insert(['name' => 'Sh. Zayed Hospital Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1707']);
        DB::table('branches')->insert(['name' => 'TECH Society Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1917']);
        DB::table('branches')->insert(['name' => 'Punjab University Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2045']);
        DB::table('branches')->insert(['name' => 'Mughalpura Workshop Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '649']);
        DB::table('branches')->insert(['name' => 'Dry Port Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '950']);
        DB::table('branches')->insert(['name' => 'Chamra Mandi Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1397']);
        DB::table('branches')->insert(['name' => 'Saddar Bazar Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1523']);
        DB::table('branches')->insert(['name' => 'Darogha wala Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2115']);
        DB::table('branches')->insert(['name' => 'Wagha Border Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '2127']);
        DB::table('branches')->insert(['name' => 'Data Darbar Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1405']);
        DB::table('branches')->insert(['name' => 'Regal Chowk Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '409']);
        DB::table('branches')->insert(['name' => 'Shahdara Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '452']);
        DB::table('branches')->insert(['name' => 'Lahore Cantt. Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '356']);
        DB::table('branches')->insert(['name' => 'Model Town Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '372']);
        DB::table('branches')->insert(['name' => 'New Garden Town Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1537']);
        DB::table('branches')->insert(['name' => 'M.M. Gulberg Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '465']);
        DB::table('branches')->insert(['name' => 'Jail Road Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '509']);
        DB::table('branches')->insert(['name' => 'Baghan Pura Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '540']);
        DB::table('branches')->insert(['name' => 'Moon Market A.I Town Branch', 'region' => 'Punjab', 'city' => 'Lahore', 'code' => '1887']);
        DB::table('branches')->insert(['name' => 'GHQ Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '330']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '394']);
        DB::table('branches')->insert(['name' => 'Murree Brewery Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '551']);
        DB::table('branches')->insert(['name' => 'PAF Chaklala Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '557']);
        DB::table('branches')->insert(['name' => 'District Council Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '638']);
        DB::table('branches')->insert(['name' => 'AOC Morgah Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '639']);
        DB::table('branches')->insert(['name' => 'Banni Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '641']);
        DB::table('branches')->insert(['name' => 'Khanna Dak Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '963']);
        DB::table('branches')->insert(['name' => 'Medical College Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1493']);
        DB::table('branches')->insert(['name' => 'Pirvadai Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1536']);
        DB::table('branches')->insert(['name' => 'Shalimar Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1623']);
        DB::table('branches')->insert(['name' => 'F-Block Pindora Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1625']);
        DB::table('branches')->insert(['name' => '502 Workshop Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1647']);
        DB::table('branches')->insert(['name' => 'Bank Road Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1858']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '395']);
        DB::table('branches')->insert(['name' => 'Satellite Town Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '399']);
        DB::table('branches')->insert(['name' => 'Passport Office Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1666']);
        DB::table('branches')->insert(['name' => 'Peshawar Road Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1508']);
        DB::table('branches')->insert(['name' => 'Cantt. Board Building Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '642']);
        DB::table('branches')->insert(['name' => 'Tench Bhatta Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '1407']);
        DB::table('branches')->insert(['name' => 'EME College Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '640']);
        DB::table('branches')->insert(['name' => 'Kahuta Branch', 'region' => 'Punjab', 'city' => 'Rawalpindi', 'code' => '442']);
        DB::table('branches')->insert(['name' => 'Railway Road Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '788']);
        DB::table('branches')->insert(['name' => 'Kunjah Road Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '973']);
        DB::table('branches')->insert(['name' => 'Circular Road Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '1453']);
        DB::table('branches')->insert(['name' => 'Ladies Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '1976']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '335']);
        DB::table('branches')->insert(['name' => 'Service Industries Branch', 'region' => 'Punjab', 'city' => 'Gujrat', 'code' => '647']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '334']);
        DB::table('branches')->insert(['name' => 'S.I.E. Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '513']);
        DB::table('branches')->insert(['name' => 'Atta Building Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '767']);
        DB::table('branches')->insert(['name' => 'Urdu Bazar Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '831']);
        DB::table('branches')->insert(['name' => 'Hide Market Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '850']);
        DB::table('branches')->insert(['name' => 'Gulabpura Cantt. Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '892']);
        DB::table('branches')->insert(['name' => 'College Road Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1448']);
        DB::table('branches')->insert(['name' => 'Satellite Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1498']);
        DB::table('branches')->insert(['name' => 'Adda Gondlanwala Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1511']);
        DB::table('branches')->insert(['name' => 'Hashmi Colony Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1852']);
        DB::table('branches')->insert(['name' => 'Civil Lines Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '333']);
        DB::table('branches')->insert(['name' => 'Chak Jagna Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1984']);
        DB::table('branches')->insert(['name' => 'Model Town Branch', 'region' => 'Punjab', 'city' => 'Gujranwala', 'code' => '1610']);
        DB::table('branches')->insert(['name' => 'Cantt. Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '404']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '405']);
        DB::table('branches')->insert(['name' => 'S.I.E. Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '608']);
        DB::table('branches')->insert(['name' => 'Mujahid Road Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '879']);
        DB::table('branches')->insert(['name' => 'Harrar Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '1596']);
        DB::table('branches')->insert(['name' => 'Rangpura Road Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '1447']);
        DB::table('branches')->insert(['name' => 'Gohadpur Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '1626']);
        DB::table('branches')->insert(['name' => 'Kotli Behram Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '956']);
        DB::table('branches')->insert(['name' => 'Ghalla Mandi Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '480']);
        DB::table('branches')->insert(['name' => 'Booth District Courts Branch', 'region' => 'Punjab', 'city' => 'Sialkot', 'code' => '403']);
        DB::table('branches')->insert(['name' => 'Main Branch, Ghallah Mandi', 'region' => 'Punjab', 'city' => 'Mandi Bahauddin', 'code' => '362']);
        DB::table('branches')->insert(['name' => 'Mangat, Phalia Road', 'region' => 'Punjab', 'city' => 'Mandi Bahauddin', 'code' => '871']);
        DB::table('branches')->insert(['name' => 'Sabzi Mandi', 'region' => 'Punjab', 'city' => 'Bahawalpur', 'code' => '1594']);
        DB::table('branches')->insert(['name' => 'Jampur Road Branch', 'region' => 'Punjab', 'city' => 'Dera Ghazi Khan', 'code' => '740']);
        DB::table('branches')->insert(['name' => 'Mauza Gadai Branch', 'region' => 'Punjab', 'city' => 'Dera Ghazi Khan', 'code' => '863']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Dera Ghazi Khan', 'code' => '326']);
        DB::table('branches')->insert(['name' => 'District Katcheri Branch', 'region' => 'Punjab', 'city' => 'Sahiwal', 'code' => '373']);
        DB::table('branches')->insert(['name' => 'Ghallah Mandi', 'region' => 'Punjab', 'city' => 'Rahim Yar Khan', 'code' => '429']);
        DB::table('branches')->insert(['name' => 'Civil Line', 'region' => 'Punjab', 'city' => 'Jhelum', 'code' => '344']);
        DB::table('branches')->insert(['name' => 'Main City Branch, (Opposite District Courts)', 'region' => 'Punjab', 'city' => 'Attock', 'code' => '315']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Punjab', 'city' => 'Sargodha', 'code' => '621']);
        DB::table('branches')->insert(['name' => 'Chenab Nagar Branch', 'region' => 'Punjab', 'city' => 'Sargodha', 'code' => '1308']);
        DB::table('branches')->insert(['name' => 'Chasma Barrage Branch', 'region' => 'Punjab', 'city' => 'Sargodha', 'code' => '502']);
        DB::table('branches')->insert(['name' => 'Iskanderabad Branch', 'region' => 'Punjab', 'city' => 'Sargodha', 'code' => '340']);
        DB::table('branches')->insert(['name' => 'Civil Lines Branch', 'region' => 'Punjab', 'city' => 'Sargodha', 'code' => '397']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Punjab', 'city' => 'Kahuta', 'code' => '442']);
        DB::table('branches')->insert(['name' => 'Main Branch NBP, SQA Furniture Market', 'region' => 'Punjab', 'city' => 'Chiniot', 'code' => '319']);
        DB::table('branches')->insert(['name' => 'G.T. Road Branch NBP', 'region' => 'Punjab', 'city' => 'Gujar Khan', 'code' => '332']);
        DB::table('branches')->insert(['name' => 'Ali-Pur Road, Vanikey Chowk.', 'region' => 'Punjab', 'city' => 'Hafiazabad', 'code' => '336']);
        DB::table('branches')->insert(['name' => 'Grain Market Branch, Minchinabad Chowk', 'region' => 'Punjab', 'city' => 'Bahawalnagar', 'code' => '307']);
        DB::table('branches')->insert(['name' => 'Main Branch. near Purani Sabz Mandi, Maatman Wala Gate.', 'region' => 'Punjab', 'city' => 'Kasur', 'code' => '348']);
        DB::table('branches')->insert(['name' => 'Katchery Bazar Branch.', 'region' => 'Punjab', 'city' => 'Okara', 'code' => '763']);
        DB::table('branches')->insert(['name' => 'Clifton Khekashan Model Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1027']);
        DB::table('branches')->insert(['name' => 'M.A. Jinnah Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '27']);
        DB::table('branches')->insert(['name' => 'F.T.C. Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '274']);
        DB::table('branches')->insert(['name' => 'Aimai House Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '18']);
        DB::table('branches')->insert(['name' => 'Saddar Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '55']);
        DB::table('branches')->insert(['name' => 'Sindhi Muslim Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '266']);
        DB::table('branches')->insert(['name' => 'North Karachi Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1086']);
        DB::table('branches')->insert(['name' => 'S.I.T.E. Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '64']);
        DB::table('branches')->insert(['name' => 'Gulshan-e-Hadeed Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '282']);
        DB::table('branches')->insert(['name' => 'Gulshan-e-Iqbal Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '2166']);
        DB::table('branches')->insert(['name' => 'C.O.D. Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '159']);
        DB::table('branches')->insert(['name' => 'New Fruit & Vegetable Market Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '270']);
        DB::table('branches')->insert(['name' => 'Rahimabad Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '256']);
        DB::table('branches')->insert(['name' => 'Tuheed Commercial Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '2158']);
        DB::table('branches')->insert(['name' => 'Passport Office Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1066']);
        DB::table('branches')->insert(['name' => 'Custon House Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '7']);
        DB::table('branches')->insert(['name' => 'Defence Housing Society Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '9']);
        DB::table('branches')->insert(['name' => 'Awami Markaz Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1920']);
        DB::table('branches')->insert(['name' => 'Malir City Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '89']);
        DB::table('branches')->insert(['name' => 'Korangi Township Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '142']);
        DB::table('branches')->insert(['name' => 'Taimoria N. Nazimabad Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '42']);
        DB::table('branches')->insert(['name' => 'Landhi Township Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '257']);
        DB::table('branches')->insert(['name' => 'Orangi Township Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1055']);
        DB::table('branches')->insert(['name' => 'Model Colony Malir Branch', 'region' => 'Sindh', 'city' => 'Karachi', 'code' => '1070']);
        DB::table('branches')->insert(['name' => 'Fatima Jinnah Road Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '14']);
        DB::table('branches')->insert(['name' => 'Market Area Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '30']);
        DB::table('branches')->insert(['name' => 'MC Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '38']);
        DB::table('branches')->insert(['name' => 'New Cloth Market Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '43']);
        DB::table('branches')->insert(['name' => 'Shahbaz Building Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '45']);
        DB::table('branches')->insert(['name' => 'Wapda Colony Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '1057']);
        DB::table('branches')->insert(['name' => 'Commercial Area Latifabad Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '1064']);
        DB::table('branches')->insert(['name' => 'Qasimabad Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '2031']);
        DB::table('branches')->insert(['name' => 'Gari Khata Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '2059']);
        DB::table('branches')->insert(['name' => 'Phuleli Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '2105']);
        DB::table('branches')->insert(['name' => 'Wadhu Wah Road Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '2141']);
        DB::table('branches')->insert(['name' => 'Latifabad Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '91']);
        DB::table('branches')->insert(['name' => 'SITE Branch', 'region' => 'Sindh', 'city' => 'Hyderabad', 'code' => '63']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Sindh', 'city' => 'Sukkur', 'code' => '65']);
        DB::table('branches')->insert(['name' => 'Bank Square Branch', 'region' => 'Sindh', 'city' => 'Larkana', 'code' => '211']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Sindh', 'city' => 'Nawabshah', 'code' => '40']);
        DB::table('branches')->insert(['name' => 'University Campus Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '388']);
        DB::table('branches')->insert(['name' => 'Namak Mandi Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '443']);
        DB::table('branches')->insert(['name' => 'Air Headquarter Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '510']);
        DB::table('branches')->insert(['name' => 'GT Road Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '517']);
        DB::table('branches')->insert(['name' => 'Khyber Bazar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '598']);
        DB::table('branches')->insert(['name' => 'Civil Secretariat Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '986']);
        DB::table('branches')->insert(['name' => 'Arbab Road Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1404']);
        DB::table('branches')->insert(['name' => 'Office Colony Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1499']);
        DB::table('branches')->insert(['name' => 'Kohat Road Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1512']);
        DB::table('branches')->insert(['name' => 'Gunj Gate Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1516']);
        DB::table('branches')->insert(['name' => 'Custom Headquarter Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1556']);
        DB::table('branches')->insert(['name' => 'Ashraf Road Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1588']);
        DB::table('branches')->insert(['name' => 'Saddar Road Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1859']);
        DB::table('branches')->insert(['name' => 'Cantt. Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '386']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '387']);
        DB::table('branches')->insert(['name' => 'Hayatabad Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1759']);
        DB::table('branches')->insert(['name' => 'University Town Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '825']);
        DB::table('branches')->insert(['name' => 'Mirch Mandi Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1510']);
        DB::table('branches')->insert(['name' => 'Shab e Qadar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Peshawar', 'code' => '1435']);
        DB::table('branches')->insert(['name' => 'Saidu Sharif', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Swat', 'code' => '1330']);
        DB::table('branches')->insert(['name' => 'Bank Square Mingora', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Swat', 'code' => '438']);
        DB::table('branches')->insert(['name' => 'Khawaja Gunj Branch (Islamic Banking Branch)', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '578']);
        DB::table('branches')->insert(['name' => 'Purdil Abad Hoti Branch (Islamic Banking Branch)', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '1971']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '365']);
        DB::table('branches')->insert(['name' => 'Dagar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '1704']);
        DB::table('branches')->insert(['name' => 'Khar Bajour Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '1595']);
        DB::table('branches')->insert(['name' => 'Saidu Sharif Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mardan', 'code' => '1330']);
        DB::table('branches')->insert(['name' => 'Sheikh Yousaf Adda Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Dera Ismail Khan', 'code' => '1429']);
        DB::table('branches')->insert(['name' => 'Kohat Development Authority (KDA) Branch, Gate#1', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Kohat', 'code' => '1803']);
        DB::table('branches')->insert(['name' => 'Cantonment Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Bannu', 'code' => '552']);
        DB::table('branches')->insert(['name' => 'Daggar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Buner', 'code' => '1704']);
        DB::table('branches')->insert(['name' => 'Balamat Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Timergarah', 'code' => '841']);
        DB::table('branches')->insert(['name' => 'Main Branch NBP, near DC Office', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Hangu', 'code' => '420']);
        DB::table('branches')->insert(['name' => 'Mandian Main Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Abbottabad', 'code' => '1348']);
        DB::table('branches')->insert(['name' => 'Shabqadar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Mohmand Agency', 'code' => '1435']);
        DB::table('branches')->insert(['name' => 'Khar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Bajur Agency', 'code' => '1595']);
        DB::table('branches')->insert(['name' => 'Parachinar Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Kurram Agency', 'code' => '385']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Miranshah', 'code' => '453']);
        DB::table('branches')->insert(['name' => 'WANA Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Wana', 'code' => '2000']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Khyber Pakhtunkhwa', 'city' => 'Chitral', 'code' => '321']);
        DB::table('branches')->insert(['name' => 'Cantonment Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '52']);
        DB::table('branches')->insert(['name' => 'Civil Secretariat Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '173']);
        DB::table('branches')->insert(['name' => 'BMC Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '184']);
        DB::table('branches')->insert(['name' => 'Industrial Estate Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '297']);
        DB::table('branches')->insert(['name' => 'Staff College Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1029']);
        DB::table('branches')->insert(['name' => 'Shara-e-Iqbal Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1059']);
        DB::table('branches')->insert(['name' => 'PAF Samungli Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1074']);
        DB::table('branches')->insert(['name' => 'Satellite Town Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1083']);
        DB::table('branches')->insert(['name' => 'Manan Chowk Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1860']);
        DB::table('branches')->insert(['name' => 'Adalat Road Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '1959']);
        DB::table('branches')->insert(['name' => 'Hazar Ganji Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '2107']);
        DB::table('branches')->insert(['name' => 'Masjid Road Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '2108']);
        DB::table('branches')->insert(['name' => 'Alamdar Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '2106']);
        DB::table('branches')->insert(['name' => 'City Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '51']);
        DB::table('branches')->insert(['name' => 'GSP` Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '112']);
        DB::table('branches')->insert(['name' => 'M.A Jinnah Road Branch', 'region' => 'Balochistan', 'city' => 'Quetta', 'code' => '233']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Balochistan', 'city' => 'Gwadar', 'code' => '79']);
        DB::table('branches')->insert(['name' => 'Turbat Kech', 'region' => 'Balochistan', 'city' => 'Kech', 'code' => '140']);
        DB::table('branches')->insert(['name' => 'Main Branch NBP, Thana Road, near Police Station.', 'region' => 'Balochistan', 'city' => 'Zhob', 'code' => '101']);
        DB::table('branches')->insert(['name' => 'Chattar Domel Branch', 'region' => 'Azad Kashmir', 'city' => 'Muzaffarabad', 'code' => '1464']);
        DB::table('branches')->insert(['name' => 'Main Branch, Bank Squire, Nangi', 'region' => 'Azad Kashmir', 'city' => 'Mirpur', 'code' => '371']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Azad Kashmir', 'city' => 'Kotli', 'code' => '441']);
        DB::table('branches')->insert(['name' => 'Arja Branch, Dhirkot Road', 'region' => 'Azad Kashmir', 'city' => 'Bagh', 'code' => '2082']);
        DB::table('branches')->insert(['name' => 'Main Branch', 'region' => 'Azad Kashmir', 'city' => 'Rawlakot', 'code' => '393']);
        DB::table('branches')->insert(['name' => 'NLI Market Branch', 'region' => 'Gilgit-Baltistan', 'city' => 'Gilgit', 'code' => '425']);
        DB::table('branches')->insert(['name' => 'Main Branch, Yadgar Chowk', 'region' => 'Gilgit-Baltistan', 'city' => 'Skardu', 'code' => '486']);
    }
}
