<?php

use Illuminate\Database\Seeder;

class RegionalOfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('regional_offices')->insert(['city' => 'Lahore', 'region' => 'Punjab', 'address' => 'Ground Floor Building 15-A, Abbott Road, Lahore (behind Police Station Qila Gujar Singh)', 'phone' => '042-9201997-9201916']);
        DB::table('regional_offices')->insert(['city' => 'Lahore - I', 'region' => 'Punjab', 'address' => '4-A, Sher Shah Block, Behind Barkat Market Near Himayat-ul-Islam Girls College, New Garden Town.', 'phone' => '042-9201836']);
        DB::table('regional_offices')->insert(['city' => 'Lahore (Bar Council)', 'region' => 'Punjab', 'address' => 'Lahore High Court Bar Association.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Lahore (Shahdrah)', 'region' => 'Punjab', 'address' => 'Saeed Park, near Ravi Toll Plaza', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Gujrat', 'region' => 'Punjab', 'address' => 'near Deona Mandi, G.T. Road', 'phone' => '053-9260200']);
        DB::table('regional_offices')->insert(['city' => 'Sialkot', 'region' => 'Punjab', 'address' => 'Zeeshan Housing Complex, Kashmir Road.', 'phone' => '0432-550096']);
        DB::table('regional_offices')->insert(['city' => 'Sialkot (Marakiwal)', 'region' => 'Punjab', 'address' => '', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Rawalpindi', 'region' => 'Punjab', 'address' => 'Opposite Station High School No.3, Gunjmandi More, Railway Workshop Road, (Near Bakery Chowk).', 'phone' => '051-9237253']);
        DB::table('regional_offices')->insert(['city' => 'Gujranwala', 'region' => 'Punjab', 'address' => 'Bukhari Road, Near Railway Station.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Bahawalpur', 'region' => 'Punjab', 'address' => 'Building # 9-A, Sawar Muhammad Hussain Road, Model Town A.', 'phone' => '0621-9255362']);
        DB::table('regional_offices')->insert(['city' => 'Faisalabad', 'region' => 'Punjab', 'address' => 'Jail Road, opposite Allied Hospital, adjacent to WASA.', 'phone' => '041-9210129']);
        DB::table('regional_offices')->insert(['city' => 'Faisalabad (Jaranwala)', 'region' => 'Punjab', 'address' => 'Nia Bazar, Heera Plaza.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Multan', 'region' => 'Punjab', 'address' => 'Alfalah Market, U-Block, Near Madni Chowk, New Multan', 'phone' => '061-9220088']);
        DB::table('regional_offices')->insert(['city' => 'Multan (Jalalpur-Pirwala)', 'region' => 'Punjab', 'address' => 'Shuja Abad Road, Opposite Special Eduction School.', 'phone' => '061-4210066']);
        DB::table('regional_offices')->insert(['city' => 'Multan (Qadirpur Rawan)', 'region' => 'Punjab', 'address' => 'Near National Bank of Pakistan, Main Road Multan.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'D.G.Khan', 'region' => 'Punjab', 'address' => 'near Medical College.', 'phone' => '0641-9260308']);
        DB::table('regional_offices')->insert(['city' => 'Sargodha', 'region' => 'Punjab', 'address' => 'Zaidi Road, Opposite LOGIX College.', 'phone' => '048-9230667']);
        DB::table('regional_offices')->insert(['city' => 'Sargodha (Bhalwal)', 'region' => 'Punjab', 'address' => 'Gujrat Road, near Bismillah CNG Station.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Attock', 'region' => 'Punjab', 'address' => 'Hunt Hall Near Session Court Chowk, Adjacent to NADRA Office, Civil Line, Attock City.', 'phone' => '057-9316211']);
        DB::table('regional_offices')->insert(['city' => 'Sahiwal', 'region' => 'Punjab', 'address' => '6-A Canal View Colony, Pak-Patan Chowk.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Kahuta', 'region' => 'Punjab', 'address' => 'near TMA Office Kallar Chowk, Opposite Sammi CNG Station, Pindi Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'GujarKhan', 'region' => 'Punjab', 'address' => 'NBP Plaza, Near Railway underpass', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Hafizabad', 'region' => 'Punjab', 'address' => 'Jami House, Mohulla Gari Awan, Sarkari Parao.', 'phone' => '5475228588']);
        DB::table('regional_offices')->insert(['city' => 'Muzaffargarh', 'region' => 'Punjab', 'address' => 'Talairy By-Pass, near Alflah Bank, Multan Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'RahimyarKhan', 'region' => 'Punjab', 'address' => 'Bank Sadiq Canal Branch, Allama Iqbal Town, near Zarai Taraqiyati Bank.', 'phone' => '068-9230433']);
        DB::table('regional_offices')->insert(['city' => 'Jhang', 'region' => 'Punjab', 'address' => 'Darul Sakina Road, Jhang Saddar.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Mandi-Bahauddin', 'region' => 'Punjab', 'address' => 'Opposite District Complex, Phalia Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Jehlum', 'region' => 'Punjab', 'address' => 'Al-Madina Center, Old GT Road, near Civil Hospitals.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Chakwal', 'region' => 'Punjab', 'address' => 'Flat # 10-11, 1st Floor Zila Council Plaza, Tehsil Chowk.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Bahawalnagar', 'region' => 'Punjab', 'address' => 'House # 8, Bublana street, East Jail Road, Hussainabad', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Kasur', 'region' => 'Punjab', 'address' => 'House # 58-A, Club Road, Abdual Shakoor Khan Colony.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Okara', 'region' => 'Punjab', 'address' => 'near Mehar Colony, Benazir Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Renala Khurd', 'region' => 'Punjab', 'address' => 'Welcome Road, Basement Faisal Bank.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Vehari', 'region' => 'Punjab', 'address' => 'House # 128, Southern Block, Sharki Colony, near Cotton Research Center.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Khanewal (Jehanian)', 'region' => 'Punjab', 'address' => 'Jehanian Industries, Khanewal Road Bypass.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Chiniott', 'region' => 'Punjab', 'address' => 'House #11/1, W-Block, Satellite Town.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Mianwali', 'region' => 'Punjab', 'address' => 'Faisal Arcade Center, Near Gulberg Chowk.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Haveli', 'region' => 'Punjab', 'address' => 'By Pass Road Forward Kahutta Near AJK Bank', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Peshawar', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Phase-5, near North West Hospital, Hayatabad.', 'phone' => '091-9217616-7']);
        DB::table('regional_offices')->insert(['city' => 'Abbotabad', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Mandian, Abdullah Market, opposite Daewoo Bus Stand, Manshera Road, Mezile Chowk.', 'phone' => '0992-385672']);
        DB::table('regional_offices')->insert(['city' => 'Bannu', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Miranshah Road, Bannu Cantt.', 'phone' => '0928-9270112, 9270207']);
        DB::table('regional_offices')->insert(['city' => 'D.I.Khan', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Near Agriculture Research Center, Main Bannu Road.', 'phone' => '0966-9280219']);
        DB::table('regional_offices')->insert(['city' => 'Kohat', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'DHQ Hospital Road, Gate#2, Phase II, KDA Township.', 'phone' => '0922-9260342']);
        DB::table('regional_offices')->insert(['city' => 'Swat (Saidu Sharif)', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Kanju Township.', 'phone' => '0946-818205, 817698']);
        DB::table('regional_offices')->insert(['city' => 'Hangu', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Darvizi Palosa, Samana Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Battagram', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'H#:1066, Ground Floor Adjacent to NADRA Office Election Office opposite Attock Petrol Pumps.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Chitral', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Ataliq House, Situated at Grils School Road, Ataleeq Bazar, Chitral', 'phone' => '0943-413690']);
        DB::table('regional_offices')->insert(['city' => 'Mardan', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'opposite DIG House, near College Chowk, near Abdual Wali Khan University.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Lower Dir (Timergara)', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'PF-96', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Buner (Daggar)', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'at Sawari, near Sultan General Hospital.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Haripur', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Near Exicise and Taxition Office, Tehsil Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Malakand (Batkhela)', 'region' => 'Khyber Pakhtunkhwa', 'address' => '', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Tank', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'opposite Town Hall Building, D.I. Khan Road.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Upper Dir', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'opposite DHQ Hospital.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Alpuri Shangila', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Opposite UBL & District Court', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Swabi', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Hajji Mastan Khan Plaza, Near HBL Bank Jehangira Road', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Laki Marwat', 'region' => 'Khyber Pakhtunkhwa', 'address' => 'Main Wali Isa Khel Road, Near Michan Khel Bus Stand', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Mohmand Agency (Ghalanay)', 'region' => 'Sindh', 'address' => 'Civil Colony', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Kurram Agency (Parachinar)', 'region' => 'Sindh', 'address' => '', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Karachi - I (West/Malir)', 'region' => 'Sindh', 'address' => 'Shahrah-e-Iraq, Near Mosque, Saddar.', 'phone' => '021-9203092-3']);
        DB::table('regional_offices')->insert(['city' => 'Karachi - II (East)', 'region' => 'Sindh', 'address' => '1st Floor, EOBI Ex (Awami Markaz), Sharah-e-Faisal, Karachi', 'phone' => '021-9203091']);
        DB::table('regional_offices')->insert(['city' => 'Karachi - III (Central)', 'region' => 'Sindh', 'address' => 'Shahrah-e-Iraq, near Mosque, Saddar.', 'phone' => '021-9203092-3']);
        DB::table('regional_offices')->insert(['city' => 'Karachi - IV (South)', 'region' => 'Sindh', 'address' => 'Shahrah-e-Iraq, near Mosque, Saddar.', 'phone' => '021-9203092-3']);
        DB::table('regional_offices')->insert(['city' => 'Larkana', 'region' => 'Sindh', 'address' => 'Jail Road, opposite Industrial Labour Colony.', 'phone' => '074-4058013-4']);
        DB::table('regional_offices')->insert(['city' => 'Hyderabad', 'region' => 'Sindh', 'address' => 'Plot No. S-3, Sind Industrial Trading Estate Area.', 'phone' => '0223-883864']);
        DB::table('regional_offices')->insert(['city' => 'Sukkar', 'region' => 'Sindh', 'address' => 'House # C-628, near Local Board, Mules Road.', 'phone' => '071-5625453']);
        DB::table('regional_offices')->insert(['city' => 'Nawabshah', 'region' => 'Sindh', 'address' => 'House no. 1-A, Sachal Sarmast Colony (Housing Society) Adjacent Society Colony', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Thatta', 'region' => 'Sindh', 'address' => 'House no. B-266, Makhdoom Hashimabad Society Talka,Makli,District, thatta', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Quetta', 'region' => 'Balochistan', 'address' => 'Arbab Barkat Ali Road, Near Railway Football Ground.', 'phone' => '081-9201762']);
        DB::table('regional_offices')->insert(['city' => 'Zhob', 'region' => 'Balochistan', 'address' => 'House # A/78, near Wapda Office, Cantonment.', 'phone' => '0822-412696']);
        DB::table('regional_offices')->insert(['city' => 'Gawadar', 'region' => 'Balochistan', 'address' => 'TTC Colony Ward.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Kech (Turbat)', 'region' => 'Balochistan', 'address' => 'Makran Plaza Turbat, infront of NADRA Office.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Dera Ala Yar (Jaffarabad)', 'region' => 'Balochistan', 'address' => 'House No. 353, Ustad Muhammad Chowk Attach, Irrigation Colony, Quetta Road', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Khuzdar', 'region' => 'Balochistan', 'address' => 'Divisional Secretariate Commissioner Office, Qallat Division.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Loralai', 'region' => 'Balochistan', 'address' => 'Pathan Kot Road, near to Jargah Hall.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Qilla Saifullah', 'region' => 'Balochistan', 'address' => 'Near Deptuy Commissioner Office', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Sibbi', 'region' => 'Balochistan', 'address' => 'Banglow no. 1883/B Ziarat Colony, Near Qalma Chowk, Jail Road', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Qilla Abdullah', 'region' => 'Balochistan', 'address' => 'Chamman, opposite D.C Office Mall Road, Talka Chamman', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Noshki', 'region' => 'Balochistan', 'address' => 'Main Market Road, Opposite PTCL Exchange Near Frontier Constabulary Office', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Panjgur', 'region' => 'Balochistan', 'address' => 'Municipal Building', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Ziarat', 'region' => 'Balochistan', 'address' => 'Al Naseeb House behind Shalimar Hotel Baldia Road', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Pishin', 'region' => 'Balochistan', 'address' => 'Babu Mohallah', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Khuzdar', 'region' => 'Balochistan', 'address' => 'Divisional Sectraite Commissioner Office, Qallat Division', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Skardu', 'region' => 'Gilgit-Baltistan', 'address' => 'Hameed Garh Chowk, near Deputy Commissioner Complex', 'phone' => '05815-920109']);
        DB::table('regional_offices')->insert(['city' => 'Gilgit', 'region' => 'Gilgit-Baltistan', 'address' => 'Building No.II, Yadgaar Chowk, Near Bait-ul-Mall, Kohmer.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Chillas', 'region' => 'Gilgit-Baltistan', 'address' => 'District Diamir, Khasra No. 426 Harpan', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Hunza', 'region' => 'Gilgit-Baltistan', 'address' => 'Regional Passport Office Aliabad', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Astore', 'region' => 'Gilgit-Baltistan', 'address' => 'Eidgah Passport Office Near Pullo Ground', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Ghanche', 'region' => 'Gilgit-Baltistan', 'address' => 'Regional Passport Office Khaplu, Baluchistan', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Ghizer', 'region' => 'Gilgit-Baltistan', 'address' => 'Regional Passport Office Gahkuch', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Skardu', 'region' => 'Gilgit-Baltistan', 'address' => 'Hameed Garh Chowk, Near DC Office', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Muzaffarabad', 'region' => 'Azad Kashmir', 'address' => 'Mir Plaza Bela Noor Shah, near Bus Stand, Abbotabad Road.', 'phone' => '058810-62792-93']);
        DB::table('regional_offices')->insert(['city' => 'Mirpur', 'region' => 'Azad Kashmir', 'address' => 'near bhutto park', 'phone' => '058610-42133']);
        DB::table('regional_offices')->insert(['city' => 'Kotli', 'region' => 'Azad Kashmir', 'address' => 'Near DC House, G & A Plaza.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Rawlakot', 'region' => 'Azad Kashmir', 'address' => 'near Baldia Chowk Bus Stand, Link Road Hajeera By-Pass. Dist. Poonch', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Bagh (Arja)', 'region' => 'Azad Kashmir', 'address' => 'Arja Bagh, Rawalakot Road, District Bagh.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Islamgarh', 'region' => 'Azad Kashmir', 'address' => 'Near Post Office Islamgarh', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Hattian', 'region' => 'Azad Kashmir', 'address' => 'Near NADRA Office, Kanda Bala, Tehsil & District, Hattian Bala', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Neelam', 'region' => 'Azad Kashmir', 'address' => 'Main Bazar,Post Office Near HBL Bank, Athmuqam', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Sudhnoti', 'region' => 'Azad Kashmir', 'address' => 'Hajimamansha Plaza, New Sudhnoti, Bazar Purana Palandri Sheher, Kashmir', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'London (UK)', 'region' => 'International', 'address' => 'Pakistan High Commission, 34 Lowndes Square, SW1X 9JN.', 'phone' => '44-0207-6649200/11']);
        DB::table('regional_offices')->insert(['city' => 'Frankfurt (Germany)', 'region' => 'International', 'address' => 'Consulate General of Pakistan, Eschenbachstrasse 28/Off, Kennedyalle, 60596, Frankfurt am Main.', 'phone' => '(0049-69)-69867850-41, Fax 698678517']);
        DB::table('regional_offices')->insert(['city' => 'Toronto (Canada)', 'region' => 'International', 'address' => '7880 Keele Street, Unit 13 Vaughan, Ontario L4K 4GL', 'phone' => '1-905-532-42, 1-905-532-9531']);
        DB::table('regional_offices')->insert(['city' => 'Rome (Italy)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Via Dellah Camilluccia, 682, 00135.', 'phone' => '(39-06)-36301775 & 3294836']);
        DB::table('regional_offices')->insert(['city' => 'New York (USA)', 'region' => 'International', 'address' => 'Embassy of Pakistan, 12 East 65th Street, NY 10065.', 'phone' => '(01)-212-879-5800 Ext 229 (fax) 517-6987']);
        DB::table('regional_offices')->insert(['city' => 'Los Angeles (USA)', 'region' => 'International', 'address' => 'Embassy of Pakistan, LA 10850 Wilshire Blvd, Suite # 1250, CA-90024.', 'phone' => '00310-4415114-4410167']);
        DB::table('regional_offices')->insert(['city' => 'Oslo (Norway)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Eckersbergs Gate 20, 0244.', 'phone' => '(47) 23136080-84']);
        DB::table('regional_offices')->insert(['city' => 'Dubai (UAE)', 'region' => 'International', 'address' => 'Consulate General of Pakistan, Bur Dubai, Khalid Bin Walid Road, P.O.Box 340.', 'phone' => '0971-4-3913600']);
        DB::table('regional_offices')->insert(['city' => 'Jeddah (KSA)', 'region' => 'International', 'address' => 'Consulate General of Pakistan, N-17, E-7 Sector Mushirefah Ibrahim Al Tassan Street (19), Building # 58, P.O.Box 182.', 'phone' => '09962-6692371']);
        DB::table('regional_offices')->insert(['city' => 'Riyadh (KSA)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Diplomatic Quarters, P.O Box 94007, Riyadh-11693', 'phone' => '0966-14884111']);
        DB::table('regional_offices')->insert(['city' => 'Abu-Dhabi (UAE)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Plot #2, Sector W59, Diplomatic Enclave, near Sheikh Zayed Military Hospital. PO Box 846', 'phone' => '971-2-4447800']);
        DB::table('regional_offices')->insert(['city' => 'Muscat(Oman)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Building # 1702, Plot # 1629/1/4, Road # 10, Way # 2133, Madina Sultan Qaboos PC RUWI', 'phone' => '24603439, 24696511']);
        DB::table('regional_offices')->insert(['city' => 'Paris (France)', 'region' => 'International', 'address' => 'Embassy of Pakistan, 18 Rue Lord Byron 75008', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Doha (Qatar)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Plot #30, Diplomatic Area, West Bay, P.O.Box 334.', 'phone' => '00974-44832525']);
        DB::table('regional_offices')->insert(['city' => 'Kuwait', 'region' => 'International', 'address' => 'Embassy of Pakistan, Villa #46, Qasima/Plot #5, Block-11, Street #101, Shahre-e-Police station, JABRIYA', 'phone' => '00965-25327649-51']);
        DB::table('regional_offices')->insert(['city' => 'Manama (Bahrain)', 'region' => 'International', 'address' => 'Embassy of Pakistan, building # 35, Road # 1901, block # 319', 'phone' => '00973-17244113, 00973-17255960']);
        DB::table('regional_offices')->insert(['city' => 'Bradford (UK)', 'region' => 'International', 'address' => 'Consul General, 12-A North Parade, BD1 3HT.', 'phone' => '(00 44 1274) 308062, 308064, 308874']);
        DB::table('regional_offices')->insert(['city' => 'Canberra (Australia)', 'region' => 'International', 'address' => '4, Timbarra Cresent, O Malley Act 2602', 'phone' => '61470342957, 61451955906']);
        DB::table('regional_offices')->insert(['city' => 'Kuala Lumpur (Malaysia)', 'region' => 'International', 'address' => '132, Jalan Ampang, 50450.', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Sydney (Australia)', 'region' => 'International', 'address' => 'Level-07 32 Martin Palace', 'phone' => '+61 2 – 92221806-7']);
        DB::table('regional_offices')->insert(['city' => 'Athens (Greece)', 'region' => 'International', 'address' => 'Embassy of Pakistan, Loukianou 6 Kolonaki 106 75', 'phone' => '0030-69040070793']);
        DB::table('regional_offices')->insert(['city' => 'Beijing (China)', 'region' => 'International', 'address' => '1-Dongzhimenwai Dajie, Sanlitun, 1. 100600', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Copenhagen (Denmark)', 'region' => 'International', 'address' => 'Valeurserj 17, 2900 Hellerup', 'phone' => '4539621188']);
        DB::table('regional_offices')->insert(['city' => 'The Hague (Netherlands)', 'region' => 'International', 'address' => 'Amaliastraat 08, 2514 Jc Den Haag', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Madrid (Spain)', 'region' => 'International', 'address' => 'Embassy of Pakistan. Call de Pedro de Valdivia, 16', 'phone' => '34915622294']);
        DB::table('regional_offices')->insert(['city' => 'Manchester (UK)', 'region' => 'International', 'address' => '137-Dickenson Road M14 5JB', 'phone' => '1612251786']);
        DB::table('regional_offices')->insert(['city' => 'Houston (USA)', 'region' => 'International', 'address' => '11850 Jones Road, TX 77070', 'phone' => '12818902223']);
        DB::table('regional_offices')->insert(['city' => 'Seoul (Korea)', 'region' => 'International', 'address' => '124-12, Itaewon Dong, Yongsan-GU', 'phone' => '8227968252']);
        DB::table('regional_offices')->insert(['city' => 'Washington DC (USA)', 'region' => 'International', 'address' => '3517, International Court NW, DC 20008', 'phone' => '202 243 6500']);
        DB::table('regional_offices')->insert(['city' => 'Dhaka (Bangladesh)', 'region' => 'International', 'address' => 'NE (C), Road No. 71, Gulshan II', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Astana (Kazakhstan)', 'region' => 'International', 'address' => '15 Floor, business Centre, Peking Palace Hotel, 27 Syganak Street.', 'phone' => '+7 7172 799 374, 799 375']);
        DB::table('regional_offices')->insert(['city' => 'Damascus (Syria)', 'region' => 'International', 'address' => 'East Mezzeh, Al-Farabi Street.', 'phone' => '963116000000']);
        DB::table('regional_offices')->insert(['city' => 'Barcelona(Spain)', 'region' => 'International', 'address' => 'Barcelona AV Sarria 271/1 08029', 'phone' => '34631444686']);
        DB::table('regional_offices')->insert(['city' => 'Tanzani', 'region' => 'International', 'address' => 'Plot No. 338, House No. MKC/1259, Maziende Street, Rose Garden Road, Mikocheni-B Dar Es Salam', 'phone' => '255790000000']);
        DB::table('regional_offices')->insert(['city' => 'Balgrade (Serbia)', 'region' => 'International', 'address' => 'Bulevar Kneza Aleksandra Karadjordjevica 62, 11040', 'phone' => '+381 11 266 1676']);
        DB::table('regional_offices')->insert(['city' => 'Romania', 'region' => 'International', 'address' => '22 Barbu Delarancea Sector-1 71304 Bucharest', 'phone' => '+4021 3187873']);
        DB::table('regional_offices')->insert(['city' => 'Baku (Azerbaijan)', 'region' => 'International', 'address' => 'Narimanov District 106 Attaturk Avenue near Khazar Television', 'phone' => '994124000000']);
        DB::table('regional_offices')->insert(['city' => 'Tashkent (Uzbekistan)', 'region' => 'International', 'address' => 'Building No. 15, Kichik Halqa Yoli Street Sobir Rahimov District.', 'phone' => '998912000000']);
        DB::table('regional_offices')->insert(['city' => 'Chicago (USA)', 'region' => 'International', 'address' => '333 N Michigan Ave Suit 728, IL 60601', 'phone' => '001312 781 1831']);
        DB::table('regional_offices')->insert(['city' => 'Pretoria (South Africa)', 'region' => 'International', 'address' => '', 'phone' => '0027 0 12 362 3965/ 362 4072/73, 0027 61 7724865']);
        DB::table('regional_offices')->insert(['city' => 'Wellington (New Zealand)', 'region' => 'International', 'address' => '182 on Slowrd Khandallah Wellington 6035', 'phone' => '006444790026-27']);
        DB::table('regional_offices')->insert(['city' => 'Stockholm (Sweden)', 'region' => 'International', 'address' => '65 Karlavagen Street, (First Floor) 10240 Stockholm', 'phone' => '+46 8 203300']);
        DB::table('regional_offices')->insert(['city' => 'Bosnia, Herzegovina', 'region' => 'International', 'address' => 'Emerika Bluma 17, 71000, Sarajevo', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Nairobi (Kenya)', 'region' => 'International', 'address' => 'St. Michaels Road, Off Church Road, Westlands', 'phone' => '+254 4443911/2']);
        DB::table('regional_offices')->insert(['city' => 'Vienna (Austria)', 'region' => 'International', 'address' => 'Hofzeile 13, A-1190', 'phone' => '+43 1 3687381-2']);
        DB::table('regional_offices')->insert(['city' => 'Kieve (Ukraine)', 'region' => 'International', 'address' => '7, Pafilovziv Per. KYIV, 01015', 'phone' => '+380 44 280 2577']);
        DB::table('regional_offices')->insert(['city' => 'Ankara (Turkey)', 'region' => 'International', 'address' => 'Gazi Osman Pasa Mah. Iran Cad No.37, Cankaya', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Colombo (Srilanka)', 'region' => 'International', 'address' => 'Embassy of Pakistan', 'phone' => '0094112055681-2']);
        DB::table('regional_offices')->insert(['city' => 'Portlouis (Mauritius)', 'region' => 'International', 'address' => '9A, Queen Mary Avenue Floreal', 'phone' => '00230 6988501-02']);
        DB::table('regional_offices')->insert(['city' => 'Birmingham (UK)', 'region' => 'International', 'address' => '10-A, The Wharf Bridge Street B1 2JS', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Hong Kong (China)', 'region' => 'International', 'address' => 'Room 803-04, 8th Floor Tung Wai commercial Building, 109-111, Gloucester Road, Wanchai', 'phone' => '+852 2827 1966']);
        DB::table('regional_offices')->insert(['city' => 'Milan (Italy)', 'region' => 'International', 'address' => 'Via Rosa Massara De Capitani-11 20158 Mialano (MI)', 'phone' => '0039-02 66703271']);
        DB::table('regional_offices')->insert(['city' => 'Berne(Switzerland)', 'region' => 'International', 'address' => 'Bernastrasse 47 3005', 'phone' => '']);
        DB::table('regional_offices')->insert(['city' => 'Istanbul (Turkey)', 'region' => 'International', 'address' => 'Gullu Sokak No 20, 3 Levent', 'phone' => '0090-212 3245827']);
        DB::table('regional_offices')->insert(['city' => 'Phnom Penh (Combodia)', 'region' => 'International', 'address' => 'H.No. 45, St.No. 310 Sangkat Boeung Keng Kang-I', 'phone' => '00855 23 996890-91']);
        DB::table('regional_offices')->insert(['city' => 'Beirut (Lebanon)', 'region' => 'International', 'address' => '8th Floor, Verdan Plaza No. 1, Saab Salam Street, Crossroad.', 'phone' => '00961 1790327']);
        DB::table('regional_offices')->insert(['city' => 'Moscow (Russia)', 'region' => 'International', 'address' => '17 Sadovaya Kudrinskaya Ul, 123001', 'phone' => '007 499 766 2320']);
        DB::table('regional_offices')->insert(['city' => 'Jakarta (Indonesia)', 'region' => 'International', 'address' => 'Jalan Mega Barat, Block E.3.9, Kav, 5-8, Seltan 12950', 'phone' => '57851829']);
        DB::table('regional_offices')->insert(['city' => 'Bishkek (Kyrgzstan)', 'region' => 'International', 'address' => '37 Servoa, Bhishkek', 'phone' => '00996-312373901']);
        DB::table('regional_offices')->insert(['city' => 'Kathmando (Nepal)', 'region' => 'International', 'address' => 'Kapan Marg Chakrapath, Maharahgunj', 'phone' => '+977 1 4375602']);
    }
}
